### ISSUE TITLE
ESC4 Bug, Detecting permissions that are not on the acl...

### ISSUE THREAD

**Issue by mfgjwaterman** [TrimarcJake/Locksmith#133]
Hi,

LockSmith Version: v2024.3

On a Windows Server 2022 PKI Infrastructure. I use the following command in an elevated PowerShell:

`Invoke-Locksmith -Scans ESC4`

The output is:

```
Technique Name                    Issue                                                                                          
--------- ----                    -----                                                                                          
ESC4      User                    CORP\Domain Users has ReadProperty, WriteProperty, ExtendedRight rights on this template       
ESC4      UserSignature           CORP\Domain Users has ReadProperty, WriteProperty, ExtendedRight rights on this template       
ESC4      ClientAuth              CORP\Domain Users has ReadProperty, WriteProperty, ExtendedRight rights on this template       
ESC4      EFS                     CORP\Domain Users has ReadProperty, WriteProperty, ExtendedRight rights on this template       
ESC4      Machine                 CORP\Domain Computers has ReadProperty, WriteProperty, ExtendedRight rights on this template   
ESC4      IPSECIntermediateOnline CORP\Domain Computers has ReadProperty, WriteProperty, ExtendedRight rights on this template   
ESC4      Workstation             CORP\Domain Computers has ReadProperty, WriteProperty, ExtendedRight rights on this template   
ESC4      RASAndIASServer         CORP\RAS and IAS Servers has ReadProperty, WriteProperty, ExtendedRight rights on this template
```
I've manually checked all the templates and can not locate the displayed permissions. Also manually in the "permissions" and the "Effective access" tab to make sure. I'm beginning to think this is a bug?

On the templates User, UserSignature, ClientAuth and EFS, "CORP\Domain Users" only has "Enroll" rights, nothing else. 
On the templates Machine, IPSECIntermediateOnline , Workstation "CORP\Domain Computers" only has "Enroll" rights, nothing else.
On the templates RASAndIASServer "CORP\RAS and IAS Servers",  only has "Enroll" rights, nothing else.

Check was done with AdsiEdit in CN=Certificate Templates,CN=Public Key Services,CN=Services,CN=Configuration,<domain>.

If you need additional information, please let me know. Happy to help out.

**Comment by TrimarcJake** [comment]
Do you get the same results with just `Invoke-Locksmith` ?

**Comment by mfgjwaterman** [comment]
Hi Jake,

yes exactly same results.

Let me if you need additional info.

**Comment by TrimarcJake** [comment]
Okie dokie. I think I see why. Which version(s) of PowerShell are you using?

**Comment by mfgjwaterman** [comment]
I use both 5.1 and 7.x. Let me know if you need a Guinea pig.

**Comment by TrimarcJake** [comment]
Do you get the same results when running from a non-elevated prompt?

**Comment by mfgjwaterman** [comment]
It's the same output on a mic medium and high. I just remembered I tested it only on 5.1. Got a warning on 7 about servermanger being required and running in compat mode. Couldn't get it to work. Anyways, different story. Let's see if we can fix it on 5,1 first.

**Comment by TrimarcJake** [comment]
Well my lab is almost rebuilt to my previous specs, so expect an update soooon

**Comment by TrimarcJake** [comment]
This PR should resolve the issue: https://github.com/TrimarcJake/Locksmith/pull/135

Let me know if that version works for you.

**Comment by mfgjwaterman** [comment]
Hello there!

Just tested this version with the same tests as before and it seems to work now. Thanks for the effort! Really appreciate you taking the time to build and fix this.

**Comment by TrimarcJake** [comment]
\o/ Thanks for testing! Expect these changes in the next release.
