### ISSUE TITLE
CA Hosts Not Being Added to $SafeUsers.

### ISSUE THREAD

**Issue by TrimarcJake** [TrimarcJake/Locksmith#138]
CA Hosts need to be able to control PKI stuff, so they should be considered Safe Users.

**Comment by TrimarcJake** [comment]
CA Hosts need to be able to control PKI stuff, so they should be considered Safe Users.

**Comment by TrimarcJake** [comment]
Ope. We were already *trying* to do this... but we're adding the DN of the CA Host instead of the SID. Should be easy fix!

**Comment by SamErde** [comment]
Oh, what do you think about saving the CA Name and SID as key value pairs in a hash table for easy reference?

**Comment by TrimarcJake** [comment]
@SamErde I thought about that a little more after our discussion this morning. We already that in the $CAObjects object.
