### ISSUE TITLE
PowerShell 7 nTSecurityDescriptor missing properties

### ISSUE THREAD

**Issue by mrhousz** [TrimarcJake/Locksmith#143]
**Environment:** 
Locksmith 2024.3, installed from PSGallery using Install-Module Locksmith
Windows 10 Enterprise 22H2, July 2024 security updates
PowerShell 7.4.4

**Issue:** 

Running Invoke-Locksmith in PowerShell 7 returns errors:

`A constructor was not found. Cannot find an appropriate constructor for type System.Security.Principal.NTAccount.`

This is due to missing object properties in the nTSecurityDescriptor object collected by Get-ADCSObject function. 

![image](https://github.com/user-attachments/assets/1a9d6c18-f9ee-4ce1-91ad-891b20c2909e)

**Potential fix/workaround:** 

https://github.com/PowerShell/PowerShell/issues/21540#issuecomment-2080330448

Import-Module Microsoft.PowerShell.Security prior to running Invoke-Locksmith results in the objects collected by Get-ADCSObject having the needed nTSecurityDescriptor properties

![image](https://github.com/user-attachments/assets/9877750e-2b6e-4d20-a923-38988d14b480)

**Comment by SamErde** [comment]
Good find. We should be able to test that and add to the module manifest so you don't need to manually import it.

**Comment by TrimarcJake** [comment]
Agreed. Should be way fix. @SamErde you wanna handle or me?

**Comment by SamErde** [comment]
On it!

**Comment by TrimarcJake** [comment]
Thank you, friend.

**Comment by mrhousz** [comment]
Thank you for this module and glad I could help. This was my first Github issue.
