### ISSUE TITLE
Spacing issue with ending sign-off message

### ISSUE THREAD

**Issue by mrhousz** [TrimarcJake/Locksmith#146]
Environment: 
Windows 10 22H2
PowerShell 7.4.4 and PowerShell 5.1

Issue: 
Display of the ending thank you message needs an additional space to format in the way intended. 
![image](https://github.com/user-attachments/assets/6f2c1350-ad39-45cf-b216-0accc8a0ea7e)

Fix: 
Add an additional space after the heart emoji
![image](https://github.com/user-attachments/assets/3586bb5c-45a0-4fee-9529-bab7670e0393)

**Comment by TrimarcJake** [comment]
Hi! Would you like to submit a PR for this one? If you're unsure how, we'd love to walk you through the process.

**Comment by mrhousz** [comment]
Sure, I like to learn new things. 🙂
________________________________

**Comment by TrimarcJake** [comment]
Perfect answer. Send me an email jakehildreth@trimarcsecurity.com and we'll figure out the best way to do this.

**Comment by mrhousz** [comment]
> Perfect answer. Send me an email [jakehildreth@trimarcsecurity.com](mailto:jakehildreth@trimarcsecurity.com) and we'll figure out the best way to do this.

I reached out to you via email.

**Comment by TrimarcJake** [comment]
Added to 2024.10
