### ISSUE TITLE
Add Prerequisites Section to README

### ISSUE THREAD

**Issue by mrhousz** [TrimarcJake/Locksmith#147]
Environment: 

Windows 10 22H2, July security updates, No RSAT
PowerShell 5.1 and PowerShell 7.4.4
Locksmith installed from PS Gallery
Invoke-Locksmith script downloaded 

Issue: 

The prompt to install Active Directory PowerShell module if it is missing only works when running Invoke-Locksmith as a script. 
![image](https://github.com/user-attachments/assets/7cac3f88-1bd1-40f7-80e3-dfbc9c958e63)

As a module, Active Directory PowerShell is required to load the module, therefore the functions added in Issue #92 are not available. 
![image](https://github.com/user-attachments/assets/331d7bdf-22ba-4a3c-8290-1ceeb313ccd7)

Potential fixes/clarifications: 

I was hesitant to open this since I don't really know that there is a 'fix' and the errors given are pretty clear, but it seemed like something that could potentially be confusing and could use some clarification in the documentation. 

Add a 'Prerequisites' to the documentation under Installation > Module?
Update comment based help to note that functions only available in script mode?

**Comment by TrimarcJake** [comment]
I agree that this isn't a bug to be fixed but is a failure of documentation. A `Prerequisites` section would be a nice addition to the README.

Do you want to handle this one after you work through resolving #146?

**Comment by mrhousz** [comment]
I'd be up for handling this one after resolving #146.

________________________________

**Comment by TrimarcJake** [comment]
Ope! Already handled. Sorry, Ray!
