### ISSUE TITLE
Switch to identifying "safe" objects by SID rather than name

### ISSUE THREAD

**Issue by lkarlslund** [TrimarcJake/Locksmith#15]
Running your excellent tool on non-english Active Directory environments trigger warnings for groups otherwise suppressed by the "SafeGroups", "SafeUsers" exclusions in your script.

For instance in German installations "Domain Admins" are named "Domänen-Admins" ...

(I had the same issue with Adalanche, and changing the queries to Well Known SIDs solved it.)

**Comment by TrimarcJake** [comment]
This has been in my mid-term goals for about month. Since you asked nicely, it's time to move it into the short-term goals!

**Comment by lkarlslund** [comment]
Just a suggestion to make your excellent tool more universal, no need to hurry

**Comment by TrimarcJake** [comment]
TBQH, I've been putting it off because I know it's going to be harder than I expect. Knowing that it will help you gives me all the incentive I need to get started on it. <3

**Comment by jakehildreth** [comment]
@lkarlslund That was easier to write than I expected! If you have a moment, can you test against a non-English AD?

**Comment by TrimarcJake** [comment]
@lkarlslund That was easier to write than I expected! If you have a moment, can you test against a non-English AD?

**Comment by lkarlslund** [comment]
Sorry, I don't have a current engagement on a localized AD at the moment, but if you're using SIDs for well known objects, and it works on an English AD, it should work on a localized on equally well.

**Comment by hipslu** [comment]
tested and confirmed to work!

**Comment by TrimarcJake** [comment]
@lkarlslund Thanks for prompting me to get this going, at least!

@hipslu Thank you for testing! May I ask which language you tested against?

**Comment by hipslu** [comment]
@TrimarcJake german

**Comment by techspence** [comment]
Can confirm the SID changes work for me, in English. Noticed there was an issue when the `IdentityReference` was already a SID. https://github.com/TrimarcJake/Locksmith/pull/16 adds a check for that so it doesn't try to translate a SID and error.

**Comment by TrimarcJake** [comment]
Can confirm. No more errors when the Identity Reference already contains a SID instead of a name.. Thanks for doing my work for me, @techspence!

And many thanks to you for testing, @hipslu!

This issue will be closed once we finish internal testing and commit to main. :D
