### ISSUE TITLE
SID Translation Error in the Find-ESC4 function

### ISSUE THREAD

**Issue by SamErde** [TrimarcJake/Locksmith#22]
I just encountered an error during SID translation in the Find-ESC4 function, and I haven't yet figured out what is causing it. This is probably related to something in my environment because we have not encountered these errors before, but I want to log it and figure it out.

```powershell
[ADMIN]: D:\Files>.\Invoke-Locksmith.ps1 -Forest REDACTED
Gathering AD CS Objects from REDACTED...
Identifying auditing issues...
Identifying AD CS templates with dangerous configurations...
Identifying AD CS template and other objects with poor access control...
Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."
At D:\Files\Invoke-Locksmith.ps1:454 char:13
+             $SID = ($Principal.Translate([System.Security.Principal.S ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException
```

I looked a few lines above this and tried running `$Principal = New-Object System.Security.Principal.NTAccount($_.nTSecurityDescriptor.Owner)` and this also resulted in an error: 

```powershell
New-Object : A constructor was not found. Cannot find an appropriate constructor for type System.Security.Principal.NTAccount.
At line:1 char:14
+ ... Principal = New-Object System.Security.Principal.NTAccount($_.nTSecur ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.Commands.NewObjectCommand
```

For some reason it is failing to get the security principal of the current user and then failing to get the SID of the user. I do want to figure out why, but as an experiment I tried this code to get the SID, and it worked:  

```powershell
Add-Type -AssemblyName System.DirectoryServices.AccountManagement            
$SID = ([System.DirectoryServices.AccountManagement.UserPrincipal]::Current).SID.Value 
```

### Systems Tested:
 - Windows Server 2016
 - Windows Server 2019
 - PowerShell 5.1
 - PowerShell 7.3.2

### Privileges Used:
 - Runas Admin
 - Domain Admin

Will add more notes as I have time to reproduce and test. Additional thoughts are welcomed!

**Comment by SamErde** [comment]
We have narrowed it down to ADCS objects that have unresolved SIDs for the `owner` attribute.

```
($ADCSObjects).Where({$_.ntSecurityDescriptor.Owner -like "O:*" })

**Comment by TrimarcJake** [comment]
@SamErde I just committed a bugfix for this issue, but I know you already fixed it in your environment!

**Comment by SamErde** [comment]
Great! I just looked and hope to have some time today to dig a little deeper into the SDDL format to make sure we’re effectively handling the cases of unresolved SIDs, regardless of where they show up.

**Comment by SamErde** [comment]
I'm curious but not fully confidence about something yet. Is the `"O:"` notation indicative of an "ownership" control? I'm looking at the "[Security Descriptor String Format](https://learn.microsoft.com/en-us/windows/win32/secauthz/security-descriptor-string-format)" docs and think this may be related. If so, we might need to change this regex depending on which ESC is being checked for (unsafe users vs unsafe owners)--or just update the functions to look for an unresolved SID instead of this specific descriptor.

**Comment by TrimarcJake** [comment]
In my experience, the "O:" is not solely found in the .nTSecurityDescriptor.Owner. It can also be found in .nTSecurityDescriptor.Access. Since we were already checking for unresolved SIDs in all functions using the '^S-1' regex selector, I updated the regex selector in all functions to '^S-1|^O:' which would check for unresolved SIDs of either type.

 I realize now that we use that SID translation code in a bunch of places; it should probably be moved into its own function!

**Comment by SamErde** [comment]
Yes! I noticed a few opportunities for that, too. Thanks for the explanation!

**Comment by SamErde** [comment]
> In my experience, the "O:" is not solely found in the .nTSecurityDescriptor.Owner. It can also be found in .nTSecurityDescriptor.Access. Since we were already checking for unresolved SIDs in all functions using the '^S-1' regex selector, I updated the regex selector in all functions to '^S-1|^O:' which would check for unresolved SIDs of either type.
> 
> Side note: I realize now that we use that SID translation code in a bunch of places; it should probably be moved into its own function!

Thanks, I finally got around to testing this. We will be ready to roll with one minor fix to your bug fix! The regex selector should be `'^(S-1|O:)')` instead of `'^S-1|^O:'` and it will work!
