### ISSUE TITLE
Feature Request: Add sample output to github readme

### ISSUE THREAD

**Issue by brandonscholet** [TrimarcJake/Locksmith#25]
I'll test it, but I'd love to see what the tool will give me in the readme

**Comment by TrimarcJake** [comment]
Added to the roadmap!

**Comment by TrimarcJake** [comment]
@brandonscholet Added examples to the examples/ folder and linked to them from the README.md. Like?

**Comment by TrimarcJake** [comment]
Completed! https://github.com/TrimarcJake/Locksmith/commit/6c5325b4b2f372dc1c580642b325711485fdd448
