### ISSUE TITLE
Improve RSAT Installation Process

### ISSUE THREAD

**Issue by TrimarcJake** [TrimarcJake/Locksmith#92]
If RSAT is not installed, Locksmith will silently install it if the user has admin rights. Instead, Locksmith should prompt the user for confirmation before installing and Import the AD PS module before continuing.

[ ] Add Confirmation dialog
[ ] Import module automatically.

**Comment by techspence** [comment]
Just finished this up. I haven't made a PR in a while, so I'm not exactly sure if I did this right so please scold me if I did not. :D https://github.com/TrimarcJake/Locksmith/pull/93

**Comment by TrimarcJake** [comment]
Merged!
